import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Header from "../../components/Header";
import SearchResult from "../../components/SearchResult";

function Search({ results }) {
  const router = useRouter();
  const pageTitle = router.query.term;

  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <hr />
      <SearchResult results={results}/> 
    </div>
  );
}

export default Search;

export async function getServerSideProps(context) {
  const { query } = context;
  const useDummyData = false;
  const startIndex=context.query.start||"0";
  const response = await axios(
    `https://www.googleapis.com/customsearch/v1?key=${process.env.API_KEY}&cx=${process.env.CONTEXT_KEY}&q=${query.term}&start=${startIndex}`
  );

  const data=response.data;

  return {
    props: {
      results:data,
    },
  };
}
